# Create a docker compose that run Meilisearch and Scrapix both latest version.
version: '3'

services:
  scrapix:
    image: scrapix:latest
    restart: always
    ports:
      - 3000:3000
    environment:
      - REDIS_URL=redis://redis:6379

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    ports:
      - 7700:7700
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=masterKey
      - MEILI_ENV=development
  
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379